
	#_ZG.o\
#	Makefile for:  MRTNS
#
#	Copyright (C) 1995 - Sanchez Computer Associates
#
#	$Id$
#	$Log:	Makefile,v $
# Revision 1.1  95/09/26  15:52:17  15:52:17  rcs ()
# New release on 09/26/95
# 
#	$Revision: 1.1 $
#
#
#
BUILD_DIR = ..

OBJECTS=\
	_CHARSET.o\
	_D.o\
	_DIR.o\
	_EDIT.o\
	_ENCRYPT.o\
	_ET.o\
	_FSEL.o\
	_G.o\
	_GCHANGE.o\
	_GCOPY.o\
	_GD.o\
	_GFIND.o\
	_GI.o\
	_GIGEN.o\
	_GO.o\
	_GOGEN.o\
	_GSEL.o\
	_GTMCONV.o\
	_ISSPL.o\
	_LNM.o\
	_MAIL.o\
	_MTAPI.o\
	_OSSCRPT.o\
	_PCNTRL.o\
	_PRIO.o\
	_QFUNC.o\
	_QUEFUNC.o\
	_RCHANGE.o\
	_RD.o\
	_RDIF.o\
	_READ.o\
	_RFIND.o\
	_RI.o\
	_RO.o\
	_RSEL.o\
	_RSET.o\
	_RTNDESC.o\
	_SCAIO.o\
	_SRV.o\
	_T.o\
	_TRMVT.o\
	_TRNLNM.o\
	_VMS.o\
	_ZBEN.o\
	_ZBREAK.o\
	_ZCHKDIR.o\
	_ZCHKPTR.o\
	_ZCTRLC.o\
	_ZD.o\
	_ZDIRCHG.o\
	_ZDISMOU.o\
	_ZEVENT.o\
	_ZEVENTR.o\
	_ZFREEB.o\
	_ZFREECK.o\
	_ZFUNC.o\
	_ZGCMP.o\
	_ZGVSTAT.o\
	_ZHEX.o\
	_ZINIT.o\
	_ZJOB.o\
	_ZM.o\
	_ZMBX.o\
	_ZMOUNT.o\
	_ZOCTAL.o\
	_ZOPEN.o\
	_ZPID.o\
	_ZPTM.o\
	_ZQUERUN.o\
	_ZQUESET.o\
	_ZQUEUE.o\
	_ZRCALLS.o\
	_ZREAD.o\
	_ZRELGI.o\
	_ZRELIN.o\
	_ZRELPIN.o\
	_ZRELRI.o\
	_ZRJ.o\
	_ZRTNCMP.o\
	_ZRTNDEL.o\
	_ZRTNLOD.o\
	_ZRTNS.o\
	_ZS.o\
	_ZSHELL.o\
	_ZSHSAVE.o\
	_ZSYS.o\
	_ZT.o\
	_ZTEXT.o\
	_ZTRANS.o\
	_ZULVLOD.o\
	_ZULVSAV.o\
	_ZUPGRD.o\
	_ZUPGRD0.o\
	_ZUPGRD1.o\
	_ZUPGRD2.o\
	_ZUPGRD3.o\
	_ZUPGRRI.o\
	_ZUSE.o\
	_ZWRITE.o

all: 	$(OBJECTS)
	@echo "SCA RTNS objects are up-to-date."
#
include ${BUILD_DIR}/rules.mk
