#!/bin/bash

SCRIPTS_PATH=${UTIL_DIR}
LOG_PATH=${ydb_dir}/log

echo "Stop replication in SECONDARY mode"

	${SCRIPTS_PATH}/replication_stop secondary > ${LOG_PATH}/stop_replication.log_`date +"%y%m%d-%H%M%S"` 2>&1

	STAT=$?

if [ ${STAT} -eq 0 ]
then
	echo "Replication stop successfully"
	exit 0
else
	echo "Replication stop fail"
	exit ${STAT}
fi
